
project_id = "cagmgtmeljxykyngxxmj"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-alerts]
verify_jwt = false
