
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      # Utilisation du script de lint spécifique pour CI
      - name: Lint
        run: npm run lint:ci
        
      # Build le projet
      - name: Build
        run: npm run build
