
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      # Suppression de l'étape type-check car elle n'existe pas dans package.json
      
      - name: Lint
        run: npm run lint
        
      # Suppression de l'étape test car elle n'existe pas dans package.json
        
      - name: Build
        run: npm run build
